// SPDX-License-Identifier: LGPL-2.1-or-later
// Port of codec2 src/mpdecode_core.c (sum-product LDPC decoder, CML-derived,
// Matthew C. Valenti / David Rowe), ldpc_codes.c and HRA_56_56.c: just what
// the FreeDV reliable-text codec uses.

using RadeSharp;

namespace RadeSharp.Text;

/// <summary><c>struct LDPC</c> for the codes used here.</summary>
internal sealed class LdpcCode
{
    public required string Name;
    public int MaxIter, DecType, QScaleFactor, RScaleFactor;
    public int CodeLength, NumberParityBits, NumberRowsHcols, MaxRowWeight, MaxColWeight;
    public required ushort[] HRows;
    public required ushort[] HCols;

    /// <summary>HRA_56_56: rate 1/2 (112,56), generated by ldpc_gen_c_h_file.m.</summary>
    public static readonly LdpcCode Hra56_56 = new()
    {
        Name = "HRA_56_56", MaxIter = 100, DecType = 0, QScaleFactor = 1, RScaleFactor = 1,
        CodeLength = 112, NumberParityBits = 56, NumberRowsHcols = 56, MaxRowWeight = 3, MaxColWeight = 3,
        HRows = [4, 33, 22, 2, 7, 12, 15, 41, 6, 2, 8, 4, 1, 7, 20, 10, 2, 1, 28, 7, 3, 25, 18, 19, 17, 15, 8, 13, 9, 12, 39, 6, 17, 32, 3, 6, 10, 18, 4, 34, 1, 14, 9, 5, 15, 12, 5, 35, 5, 17, 16, 36, 20, 9, 34, 33, 14, 46, 39, 27, 43, 22, 19, 45, 16, 23, 31, 52, 3, 8, 51, 13, 31, 11, 31, 36, 11, 28, 30, 21, 38, 26, 42, 29, 23, 33, 45, 19, 28, 40, 10, 23, 41, 25, 29, 36, 29, 49, 38, 11, 30, 42, 16, 37, 49, 35, 18, 47, 24, 25, 54, 34, 41, 55, 47, 44, 56, 46, 20, 55, 21, 40, 37, 53, 13, 32, 52, 22, 32, 24, 44, 42, 49, 38, 48, 24, 56, 48, 50, 39, 26, 50, 54, 26, 37, 56, 14, 27, 46, 44, 45, 43, 53, 52, 40, 21, 51, 47, 30, 50, 51, 43, 27, 54, 53, 48, 55, 35],
        HCols = [13, 4, 13, 1, 44, 9, 5, 11, 29, 16, 18, 6, 13, 1, 7, 9, 25, 23, 7, 7, 9, 3, 10, 18, 22, 26, 4, 19, 28, 23, 11, 14, 2, 40, 48, 20, 11, 22, 3, 10, 1, 20, 5, 4, 8, 2, 3, 23, 21, 27, 15, 12, 12, 31, 2, 5, 18, 10, 21, 12, 47, 32, 14, 14, 43, 35, 21, 30, 16, 35, 26, 47, 33, 38, 24, 15, 24, 6, 29, 24, 38, 29, 36, 22, 39, 45, 17, 17, 30, 55, 50, 40, 33, 25, 28, 34, 8, 27, 40, 19, 31, 6, 46, 26, 42, 30, 45, 15, 41, 52, 8, 25, 41, 17, 35, 39, 49, 36, 20, 27, 54, 37, 44, 46, 28, 42, 45, 51, 50, 51, 32, 53, 44, 16, 36, 53, 54, 32, 51, 33, 41, 47, 19, 34, 56, 56, 56, 52, 48, 43, 31, 43, 37, 46, 50, 38, 39, 37, 52, 54, 49, 48, 49, 42, 53, 55, 55, 34],
    };
}

internal static class Ldpc
{
    private struct CSubNode { public ushort Index, Socket; public float Message; }
    private struct CNode { public int Degree; public CSubNode[] Subs; }
    private struct VSubNode { public ushort Index, Socket; public float Message; public byte Sign; }
    private struct VNode { public int Degree; public float InitialValue; public VSubNode[] Subs; }

    /// <summary><c>encode</c>: accumulator-based parity for the HRA codes.</summary>
    public static void Encode(LdpcCode ldpc, ReadOnlySpan<byte> ibits, Span<byte> pbits)
    {
        uint prev = 0;
        for (int p = 0; p < ldpc.NumberParityBits; p++)
        {
            uint par = 0;
            for (int i = 0; i < ldpc.MaxRowWeight; i++)
            {
                int ind = ldpc.HRows[p + i * ldpc.NumberParityBits];
                if (ind != 0) par = par + ibits[ind - 1];
            }
            uint tmp = (par + prev) & 1;
            prev = tmp;
            pbits[p] = (byte)tmp;
        }
    }

    private const double Ajian = -0.24904163195436;
    private const double Tjian = 2.50681740420944;

    /// <summary><c>max_star0</c>: linear-log-MAP.</summary>
    private static float MaxStar0(float delta1, float delta2)
    {
        float diff = delta2 - delta1;
        if (diff > Tjian) return delta2;
        if (diff < -Tjian) return delta1;
        if (diff > 0) return (float)(delta2 + Ajian * (diff - Tjian));
        return (float)(delta1 - Ajian * (diff + Tjian));
    }

    private static void InitCVNodes(CNode[] c, int shift, int npb, int maxRowWeight, ushort[] hRows, bool h1,
        int codeLength, VNode[] v, int nRowsHcols, ushort[] hCols, int maxColWeight, int decType, ReadOnlySpan<float> input)
    {
        if (shift == 0)
        {
            for (int i = 0; i < npb; i++)
            {
                int count = 0;
                for (int j = 0; j < maxRowWeight; j++) if (hRows[i + j * npb] > 0) count++;
                c[i].Degree = count;
                if (h1) c[i].Degree = i == 0 ? count + 1 : count + 2;
            }
        }
        else
        {
            int cnt = 0;
            for (int i = 0; i < npb / shift; i++)
                for (int k = 0; k < shift; k++)
                {
                    int count = 0;
                    for (int j = 0; j < maxRowWeight; j++) if (hRows[cnt + j * npb] > 0) count++;
                    c[cnt].Degree = (i == 0 || i == npb / shift - 1) ? count + 1 : count + 2;
                    cnt++;
                }
        }

        if (h1)
        {
            if (shift == 0)
            {
                for (int i = 0; i < npb; i++)
                {
                    c[i].Subs = new CSubNode[c[i].Degree];
                    int j;
                    for (j = 0; j < c[i].Degree - 2; j++) c[i].Subs[j].Index = (ushort)(hRows[i + j * npb] - 1);
                    j = c[i].Degree - 2;
                    c[i].Subs[j].Index = i == 0 ? (ushort)(hRows[i + j * npb] - 1) : (ushort)(codeLength - npb + i - 1);
                    j = c[i].Degree - 1;
                    c[i].Subs[j].Index = (ushort)(codeLength - npb + i);
                }
            }
            if (shift > 0)
            {
                int cnt = 0;
                for (int i = 0; i < npb / shift; i++)
                    for (int k = 0; k < shift; k++)
                    {
                        c[cnt].Subs = new CSubNode[c[cnt].Degree];
                        int j;
                        for (j = 0; j < c[cnt].Degree - 2; j++) c[cnt].Subs[j].Index = (ushort)(hRows[cnt + j * npb] - 1);
                        j = c[cnt].Degree - 2;
                        c[cnt].Subs[j].Index = (i == 0 || i == npb / shift - 1)
                            ? (ushort)(hRows[cnt + j * npb] - 1)
                            : (ushort)(codeLength - npb + k + shift * i);
                        j = c[cnt].Degree - 1;
                        c[cnt].Subs[j].Index = (ushort)(codeLength - npb + k + shift * (i + 1));
                        if (i == npb / shift - 1) c[cnt].Subs[j].Index = (ushort)(codeLength - npb + k + shift * i);
                        cnt++;
                    }
            }
        }
        else
        {
            for (int i = 0; i < npb; i++)
            {
                c[i].Subs = new CSubNode[c[i].Degree];
                for (int j = 0; j < c[i].Degree; j++) c[i].Subs[j].Index = (ushort)(hRows[i + j * npb] - 1);
            }
        }

        for (int i = 0; i < codeLength - npb + shift; i++)
        {
            int count = 0;
            for (int j = 0; j < maxColWeight; j++) if (hCols[i + j * nRowsHcols] > 0) count++;
            v[i].Degree = count;
        }
        for (int i = codeLength - npb + shift; i < codeLength; i++)
        {
            if (h1) v[i].Degree = i != codeLength - 1 ? 2 : 1;
            else
            {
                int count = 0;
                for (int j = 0; j < maxColWeight; j++) if (hCols[i + j * nRowsHcols] > 0) count++;
                v[i].Degree = count;
            }
        }
        if (shift > 0) v[codeLength - 1].Degree++;

        for (int i = 0; i < codeLength; i++)
        {
            v[i].Subs = new VSubNode[v[i].Degree];
            v[i].InitialValue = input[i];
            int count = 0;
            for (int j = 0; j < v[i].Degree; j++)
            {
                if (h1 && i >= codeLength - npb + shift)
                {
                    v[i].Subs[j].Index = (ushort)(i - (codeLength - npb + shift) + count);
                    count += shift == 0 ? 1 : shift;
                }
                else v[i].Subs[j].Index = (ushort)(hCols[i + j * nRowsHcols] - 1);

                ref var cn = ref c[v[i].Subs[j].Index];
                for (int ci = 0; ci < cn.Degree; ci++)
                    if (cn.Subs[ci].Index == i)
                    {
                        v[i].Subs[j].Socket = (ushort)ci;
                        break;
                    }
                v[i].Subs[j].Message = decType == 1 ? MathF.Abs(input[i]) : Phi0.Compute(MathF.Abs(input[i]));
                if (input[i] < 0) v[i].Subs[j].Sign = 1;
            }
        }

        for (int i = 0; i < npb; i++)
            for (int j = 0; j < c[i].Degree; j++)
            {
                ref var vn = ref v[c[i].Subs[j].Index];
                for (int vi = 0; vi < vn.Degree; vi++)
                    if (vn.Subs[vi].Index == i)
                    {
                        c[i].Subs[j].Socket = (ushort)vi;
                        break;
                    }
            }
    }

    private static int SumProduct(ref int parityCheckCount, Span<byte> decodedBits, CNode[] c, VNode[] v,
        int codeLength, int npb, int maxIter, ReadOnlySpan<int> data)
    {
        int result = maxIter;
        for (int iter = 0; iter < maxIter; iter++)
        {
            decodedBits[..codeLength].Clear();
            int bitErrors = 0;

            // update r
            int ssum = 0;
            for (int j = 0; j < npb; j++)
            {
                ref var s0 = ref v[c[j].Subs[0].Index].Subs[c[j].Subs[0].Socket];
                int sign = s0.Sign;
                float phiSum = s0.Message;
                for (int i = 1; i < c[j].Degree; i++)
                {
                    ref var cp = ref c[j].Subs[i];
                    ref var vp = ref v[cp.Index].Subs[cp.Socket];
                    phiSum += vp.Message;
                    sign ^= vp.Sign;
                }
                if (sign == 0) ssum++;
                for (int i = 0; i < c[j].Degree; i++)
                {
                    ref var cp = ref c[j].Subs[i];
                    ref var vp = ref v[cp.Index].Subs[cp.Socket];
                    cp.Message = (sign ^ vp.Sign) != 0 ? -Phi0.Compute(phiSum - vp.Message) : Phi0.Compute(phiSum - vp.Message);
                }
            }

            // update q
            for (int i = 0; i < codeLength; i++)
            {
                float qi = v[i].InitialValue;
                for (int j = 0; j < v[i].Degree; j++)
                {
                    ref var vp = ref v[i].Subs[j];
                    qi += c[vp.Index].Subs[vp.Socket].Message;
                }
                if (qi < 0) decodedBits[i] = 1;
                for (int j = 0; j < v[i].Degree; j++)
                {
                    ref var vp = ref v[i].Subs[j];
                    float tempSum = qi - c[vp.Index].Subs[vp.Socket].Message;
                    vp.Message = Phi0.Compute(MathF.Abs(tempSum));
                    vp.Sign = tempSum > 0 ? (byte)0 : (byte)1;
                }
            }

            // count data bit errors, assuming that it is systematic
            for (int i = 0; i < codeLength - npb; i++) if (decodedBits[i] != data[i]) bitErrors++;
            if (bitErrors == 0)
            {
                result = iter + 1;
                break;
            }
            parityCheckCount = ssum;
            if (ssum == npb)
            {
                result = iter + 1;
                break;
            }
        }
        return result;
    }

    /// <summary><c>run_ldpc_decoder</c>: returns iterations used; <paramref name="outBits"/> gets CodeLength hard bits.</summary>
    public static int RunDecoder(LdpcCode ldpc, Span<byte> outBits, ReadOnlySpan<float> input, ref int parityCheckCount)
    {
        int codeLength = ldpc.CodeLength, npb = ldpc.NumberParityBits, nRows = ldpc.NumberRowsHcols;
        Span<byte> decodedBits = stackalloc byte[codeLength];
        int shift = npb + nRows - codeLength;
        bool h1;
        if (nRows == codeLength)
        {
            h1 = false;
            shift = 0;
        }
        else h1 = true;
        var c = new CNode[npb];
        var v = new VNode[codeLength];
        InitCVNodes(c, shift, npb, ldpc.MaxRowWeight, ldpc.HRows, h1, codeLength, v, nRows, ldpc.HCols, ldpc.MaxColWeight, ldpc.DecType, input);
        Span<int> dataInt = stackalloc int[codeLength - npb];
        dataInt.Clear();
        decodedBits.Clear();
        int iter = SumProduct(ref parityCheckCount, decodedBits, c, v, codeLength, npb, ldpc.MaxIter, dataInt);
        decodedBits.CopyTo(outBits);
        return iter;
    }

    private static readonly RadeComp[] SMatrix = [new(1.0f, 0.0f), new(0.0f, 1.0f), new(0.0f, -1.0f), new(-1.0f, 0.0f)];

    /// <summary><c>symbols_to_llrs</c> (Demod2D + Somap for QPSK).</summary>
    public static void SymbolsToLlrs(Span<float> llr, ReadOnlySpan<RadeComp> rx, ReadOnlySpan<float> rxAmps, float esNo, float meanAmp, int nsyms)
    {
        const int M = 4, bps = 2;
        Span<float> symbolLikelihood = stackalloc float[nsyms * M];
        Span<float> bitLikelihood = stackalloc float[nsyms * bps];
        for (int i = 0; i < nsyms; i++)
            for (int j = 0; j < M; j++)
            {
                float tempsr = rxAmps[i] * SMatrix[j].Real / meanAmp;
                float tempsi = rxAmps[i] * SMatrix[j].Imag / meanAmp;
                float er = rx[i].Real / meanAmp - tempsr;
                float ei = rx[i].Imag / meanAmp - tempsi;
                symbolLikelihood[i * M + j] = -esNo * (er * er + ei * ei);
            }
        Span<float> num = stackalloc float[bps];
        Span<float> den = stackalloc float[bps];
        for (int n = 0; n < nsyms; n++)
        {
            for (int k = 0; k < bps; k++)
            {
                num[k] = -1000000;
                den[k] = -1000000;
            }
            for (int i = 0; i < M; i++)
            {
                float metric = symbolLikelihood[n * M + i];
                int mask = 1 << (bps - 1);
                for (int k = 0; k < bps; k++)
                {
                    if ((mask & i) != 0) num[k] = MaxStar0(num[k], metric);
                    else den[k] = MaxStar0(den[k], metric);
                    mask >>= 1;
                }
            }
            for (int k = 0; k < bps; k++) bitLikelihood[bps * n + k] = num[k] - den[k];
        }
        for (int i = 0; i < nsyms * bps; i++) llr[i] = -bitLikelihood[i];
    }
}
