<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\RadeSharp\RadeSharp.csproj" />
    <ProjectReference Include="..\..\src\RadeSharp.Text\RadeSharp.Text.csproj" />
  </ItemGroup>
</Project>
