#!/usr/bin/env python3
"""Mechanically translates codec2 src/phi0.c into src/RadeSharp.Text/Phi0.cs.

usage: gen_phi0.py <phi0.c> <Phi0.cs>
"""
import re, sys

src = open(sys.argv[1]).read()
body = src[src.index('float phi0(float xf) {'):]
body = body.replace('float phi0(float xf) {', 'public static float Compute(float xf)\n{')
body = body.replace('int32_t x = SI16(xf);', 'int x = Si16(xf);')
body = re.sub(r'SI16\(', 'Si16(', body)
out = '''// SPDX-License-Identifier: LGPL-2.1-or-later
// <auto-generated>
// Mechanical translation of codec2 src/phi0.c (David Rowe) by
// scripts/gen_phi0.py; regenerate rather than edit (see UPDATING.md).
// </auto-generated>

namespace RadeSharp.Text;

/// <summary>codec2 <c>phi0()</c>: fixed-point indexed approximation of log((e^x+1)/(e^x-1)).</summary>
internal static class Phi0
{
    // SI16(f) = (int32_t)(f * (1 << 16)); float->int conversion saturates in .NET.
    private static int Si16(float f) => (int)(f * (1 << 16));

''' + '\n'.join(('    ' + l) if l.strip() else l for l in body.splitlines()) + '\n}\n'
open(sys.argv[2], 'w').write(out)
