#!/usr/bin/env python3
"""Generates the C# model binding classes from the init_*() functions of the
auto-generated C weight files (rade_c *_data.c, Opus fargan_data.c/pitchdnn_data.c).

Field names keep the C spelling so a diff against a new upstream version maps
one-to-one. Re-run whenever upstream regenerates its weights (see UPDATING.md).

usage: gen_models.py <out_dir> <name>=<path/to/x_data.c>:<ClassName> ...
"""
import re, sys, pathlib

INIT_RE = re.compile(r'int init_(\w+)\((\w+) \*model, const WeightArray \*arrays(?:, int (\w+))?\) \{(.*?)\n\}', re.S)
LIN_RE = re.compile(r'linear_init\(&model->(\w+), arrays, (.*?)\)\) return 1;')
CONV_RE = re.compile(r'conv2d_init\(&model->(\w+), arrays, (.*?)\)\) return 1;')

def cs_arg(a):
    a = a.strip()
    return 'null' if a == 'NULL' else a

def gen(src, cls, source_label):
    text = pathlib.Path(src).read_text()
    m = INIT_RE.search(text)
    if not m:
        sys.exit(f'{src}: no init_ function')
    fn, _ctype, extra, body = m.groups()
    fields, inits = [], []
    for line in body.strip().splitlines():
        lm, cm = LIN_RE.search(line), CONV_RE.search(line)
        if lm:
            name, args = lm.groups()
            fields.append(f'    public readonly LinearLayer {name};')
            inits.append(f'        {name} = LinearLayer.Init(arrays, {", ".join(cs_arg(a) for a in args.split(","))});')
        elif cm:
            name, args = cm.groups()
            fields.append(f'    public readonly Conv2dLayer {name};')
            inits.append(f'        {name} = Conv2dLayer.Init(arrays, {", ".join(cs_arg(a) for a in args.split(","))});')
        elif line.strip() != 'return 0;':
            sys.exit(f'{src}: unrecognised init line: {line}')
    ctor_args = 'WeightSet arrays' + (f', int {extra}' if extra else '')
    return f'''// <auto-generated>
// Generated by scripts/gen_models.py from {source_label} (init_{fn}). Do not edit.
// </auto-generated>
#pragma warning disable IDE1006 // C field names are kept for traceability to upstream

using RadeSharp.Nnet;

namespace RadeSharp.Models;

internal sealed class {cls}
{{
{chr(10).join(fields)}

    public {cls}({ctor_args})
    {{
{chr(10).join(inits)}
    }}
}}
'''

out = pathlib.Path(sys.argv[1])
out.mkdir(parents=True, exist_ok=True)
for spec in sys.argv[2:]:
    label, rest = spec.split('=', 1)
    path, cls = rest.rsplit(':', 1)
    (out / f'{cls}.g.cs').write_text(gen(path, cls, label))
    print(f'{cls}.g.cs <- {label}')
